services:
  - type: web
    name: connucmatrix
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
